---
- name: Install Java
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure Java is installed 
      package:
        name: openjdk-11-jdk
        state: present
      

    - name: Verify Java installation
      command: java -version
      register: java_version

    - name: Show Java version
      debug:
        msg: "Java version installed: {{ java_version.stdout }}"

